# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UOOYKDSSB1z0hGue7yK6eEDAhLfSPoZ_
"""

import streamlit as st

def show_header():
    st.markdown('<div class="header">', unsafe_allow_html=True)
    st.image("logo.jpeg", width=400)
    st.title("📄 Chatyfile")
    st.markdown('</div>', unsafe_allow_html=True)

def show_footer():
    st.markdown("""
    <div class="footer">
        <p>© 2025 Chatyfile. Todos los derechos reservados.</p>
    </div>
    """, unsafe_allow_html=True)

def show_sidebar():
    st.sidebar.header("🤖 DATOS")