# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UOOYKDSSB1z0hGue7yK6eEDAhLfSPoZ_
"""

import pandas as pd

def load_data(uploaded_file):
    return pd.read_csv(uploaded_file)