# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UOOYKDSSB1z0hGue7yK6eEDAhLfSPoZ_
"""

import streamlit as st
from layout import show_header, show_footer, show_sidebar
from config import configure_page, set_custom_styles
from chat_engine import handle_chat
from utils import load_data

configure_page()
set_custom_styles()
show_header()

st.markdown("### ¡Bienvenido a Chatyfile!\nSube tu archivo y haz preguntas sobre tus datos.")

show_sidebar()
uploaded_file = st.sidebar.file_uploader("Sube tu archivo", type=["csv"])

show_footer()

if uploaded_file:
    df = load_data(uploaded_file)
    handle_chat(df)
else:
    st.warning("Por favor, sube un archivo para continuar.")
