# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UOOYKDSSB1z0hGue7yK6eEDAhLfSPoZ_
"""

import streamlit as st

def configure_page():
    st.set_page_config(
        page_title="Chatyfile",
        page_icon="📄",
        layout="wide",
        initial_sidebar_state="expanded"
    )

def set_custom_styles():
    st.markdown("""
    <style>
    .stApp { background-color: #f0f2f6; }
    .header {
        display: flex; align-items: center; padding: 10px;
        background-color: #1f77b4; border-radius: 10px;
    }
    .footer {
        text-align: center; padding: 10px; background-color: #1f77b4;
        color: white; position: fixed; bottom: 0; width: 100%;
    }
    </style>
    """, unsafe_allow_html=True)
